import type { ClientBranding } from "./types";

/*
  Hotel branding palettes.

  Each palette maps to the CSS variables declared in src/styles.css.
  Color values are RGB triplets ("r g b") so Tailwind's alpha syntax works.
  Every palette keeps brand-800 readable on brand-50 and white on the CTA
  (WCAG AA for normal text).

  The whole app is themed from a single palette: the brand scale, the call to
  action color (--ink, derived from brand-800 so it changes with the palette),
  and the decorative card tints (generated by hue-rotating the brand color so
  every accent still belongs to the chosen family — see applyBrandingToDocument).
  The only fixed colors are the semantic status hues (ready / attention /
  blocked), which must stay recognizable across every palette.
*/

export type BrandPalette = {
  id: string;
  name: string;
  tagline: string;
  brand: {
    50: string;
    100: string;
    200: string;
    300: string;
    700: string;
    800: string;
    900: string;
    950: string;
  };
  background: {
    base: string;
    from: string;
    via: string;
    to: string;
  };
};

export const BRAND_PALETTES: BrandPalette[] = [
  {
    id: "innpilotDefault",
    name: "InnPilot Default",
    tagline: "Graphite, warm grey, and restrained oxblood",
    brand: {
      50: "253 246 246",
      100: "248 231 232",
      200: "239 204 206",
      300: "222 157 161",
      700: "153 43 51",
      800: "126 32 39",
      900: "101 25 31",
      950: "57 13 17",
    },
    background: {
      base: "#f2f2f1",
      from: "#fafafa",
      via: "#efefee",
      to: "#f7f7f6",
    },
  },
  {
    id: "amethystSuite",
    name: "Amethyst Suite",
    tagline: "Violet and silver, the InnPilot signature",
    brand: {
      50: "245 243 255",
      100: "237 233 254",
      200: "221 214 254",
      300: "196 181 253",
      700: "124 58 237",
      800: "109 40 217",
      900: "91 33 182",
      950: "49 20 99",
    },
    background: {
      base: "#f2f1f7",
      from: "#faf9fe",
      via: "#efecf8",
      to: "#f3f1f6",
    },
  },
  {
    id: "coastalHotel",
    name: "Coastal Hotel",
    tagline: "Marine blue, fresh and bright",
    brand: {
      50: "240 247 252",
      100: "217 236 247",
      200: "179 217 239",
      300: "124 189 228",
      700: "22 97 143",
      800: "19 79 117",
      900: "17 64 94",
      950: "7 39 60",
    },
    background: {
      base: "#eef3f6",
      from: "#f7fafc",
      via: "#e4eef4",
      to: "#eef2ef",
    },
  },
  {
    id: "midnightNavy",
    name: "Midnight Navy",
    tagline: "Deep indigo, quiet and confident",
    brand: {
      50: "240 243 250",
      100: "224 230 245",
      200: "196 207 235",
      300: "150 169 219",
      700: "47 70 140",
      800: "37 56 117",
      900: "30 45 95",
      950: "17 26 56",
    },
    background: {
      base: "#eef0f6",
      from: "#f7f9fc",
      via: "#e6eaf3",
      to: "#eef0f4",
    },
  },
  {
    id: "luxuryGold",
    name: "Luxury Gold",
    tagline: "Bronze and ivory, quietly grand",
    brand: {
      50: "251 247 238",
      100: "245 234 210",
      200: "237 220 176",
      300: "221 193 131",
      700: "138 100 32",
      800: "116 83 26",
      900: "94 67 21",
      950: "58 42 12",
    },
    background: {
      base: "#f4efe6",
      from: "#fdfaf4",
      via: "#f4eee2",
      to: "#efe7d8",
    },
  },
  {
    id: "sunsetCoral",
    name: "Sunset Coral",
    tagline: "Warm coral, golden hour glow",
    brand: {
      50: "254 244 240",
      100: "253 230 222",
      200: "250 202 186",
      300: "245 162 138",
      700: "192 67 38",
      800: "162 54 32",
      900: "133 45 27",
      950: "79 26 16",
    },
    background: {
      base: "#f6efea",
      from: "#fdf7f3",
      via: "#f5e9e2",
      to: "#f1ece6",
    },
  },
  {
    id: "roseBoutique",
    name: "Rose Boutique",
    tagline: "Soft rose, romantic and refined",
    brand: {
      50: "253 242 248",
      100: "252 231 243",
      200: "251 207 232",
      300: "249 168 212",
      700: "190 41 100",
      800: "159 34 84",
      900: "131 30 70",
      950: "78 18 42",
    },
    background: {
      base: "#f7eef3",
      from: "#fdf6f9",
      via: "#f6e8f0",
      to: "#f2ecef",
    },
  },
  {
    id: "alpineSpa",
    name: "Alpine Spa",
    tagline: "Sage and pine, soft and restful",
    brand: {
      50: "243 248 244",
      100: "224 238 227",
      200: "194 221 200",
      300: "151 194 161",
      700: "46 107 64",
      800: "39 88 53",
      900: "33 72 45",
      950: "18 42 26",
    },
    background: {
      base: "#eef3ee",
      from: "#f7faf7",
      via: "#e8f0e9",
      to: "#f1efe7",
    },
  },
  {
    id: "forestEmerald",
    name: "Forest Emerald",
    tagline: "Rich emerald, lush and grounded",
    brand: {
      50: "240 251 247",
      100: "209 245 232",
      200: "167 235 213",
      300: "110 218 184",
      700: "21 110 80",
      800: "17 90 66",
      900: "15 74 55",
      950: "7 40 30",
    },
    background: {
      base: "#edf4f0",
      from: "#f6fbf8",
      via: "#e6f1ec",
      to: "#eff2ec",
    },
  },
  {
    id: "mediterranean",
    name: "Mediterranean",
    tagline: "Terracotta warmth, sunlit stone",
    brand: {
      50: "253 244 240",
      100: "250 227 216",
      200: "243 200 179",
      300: "232 161 129",
      700: "173 74 34",
      800: "145 62 29",
      900: "118 51 25",
      950: "70 29 13",
    },
    background: {
      base: "#f5f0ea",
      from: "#fcf8f3",
      via: "#f3ebe2",
      to: "#eef0ea",
    },
  },
  {
    id: "slateHarbor",
    name: "Slate Harbor",
    tagline: "Cool blue-grey, calm and professional",
    brand: {
      50: "244 247 250",
      100: "231 237 242",
      200: "205 216 226",
      300: "156 175 192",
      700: "51 73 94",
      800: "42 60 78",
      900: "34 49 64",
      950: "18 27 36",
    },
    background: {
      base: "#eef1f4",
      from: "#f8fafb",
      via: "#e7ecf1",
      to: "#f1f2f1",
    },
  },
  {
    id: "modernMinimal",
    name: "Modern Minimal",
    tagline: "Graphite monochrome, clean lines",
    brand: {
      50: "246 247 248",
      100: "233 235 238",
      200: "211 215 221",
      300: "174 181 192",
      700: "63 71 84",
      800: "52 59 70",
      900: "43 49 58",
      950: "21 24 30",
    },
    background: {
      base: "#f1f2f4",
      from: "#fafbfc",
      via: "#edeff2",
      to: "#f2f2f0",
    },
  },
];

export const DEFAULT_PALETTE_ID = "innpilotDefault";

/** Palette ids the backend accepts — keep in sync with KNOWN_PALETTES in config.rs. */
export const PALETTE_IDS = BRAND_PALETTES.map((palette) => palette.id);

export const MAX_WATERMARK_OPACITY_PERCENT = 30;

export const DEFAULT_BRANDING: ClientBranding = {
  palette: DEFAULT_PALETTE_ID,
  logoPath: "",
  primaryColor: "",
  accentColor: "",
  backgroundStyle: "soft",
  watermarkEnabled: true,
  watermarkOpacity: 6,
};

export function resolvePalette(paletteId?: string): BrandPalette {
  return (
    BRAND_PALETTES.find((palette) => palette.id === paletteId) ?? BRAND_PALETTES[0]
  );
}

/*
  Decorative card tints, derived from the active palette.

  Each slot rotates the brand hue by a small, harmonious offset so accents feel
  varied yet always belong to the chosen palette (a monochrome palette yields
  elegant greys; a vivid one yields a cohesive multi-hue set). The slot keys are
  stable identifiers used by tints.ts — their names are historical and do not
  imply a fixed hue.
*/
const TINT_SLOTS: { key: string; hueOffset: number }[] = [
  { key: "brand", hueOffset: 0 },
  { key: "sky", hueOffset: 30 },
  { key: "violet", hueOffset: 60 },
  { key: "amber", hueOffset: -32 },
  { key: "emerald", hueOffset: -62 },
  { key: "rose", hueOffset: 95 },
];

/** Applies hotel branding to the design tokens in src/styles.css. */
export function applyBrandingToDocument(branding?: ClientBranding | null) {
  const resolved = branding ?? DEFAULT_BRANDING;
  const palette = BRAND_PALETTES[0];
  const root = document.documentElement.style;

  const brandScale = { ...palette.brand };
  void resolved.palette;
  void resolved.primaryColor;
  void resolved.accentColor;
  root.setProperty("--brand-50", brandScale[50]);
  root.setProperty("--brand-100", brandScale[100]);
  root.setProperty("--brand-200", brandScale[200]);
  root.setProperty("--brand-300", brandScale[300]);
  root.setProperty("--brand-700", brandScale[700]);
  root.setProperty("--brand-800", brandScale[800]);
  root.setProperty("--brand-900", brandScale[900]);
  root.setProperty("--brand-950", brandScale[950]);

  // Black carries selection and hierarchy; oxblood is reserved for actions.
  root.setProperty("--ink", "24 24 27");
  root.setProperty("--ink-soft", "39 39 42");
  root.setProperty("--cta", brandScale[700]);
  root.setProperty("--cta-soft", brandScale[800]);

  // Decorative tints stay neutral so cards do not compete with primary actions.
  const [baseHue] = rgbToHsl(brandScale[700]);
  const baseSat = 0;
  for (const slot of TINT_SLOTS) {
    if (slot.key === "brand") {
      setTintVars(root, slot.key, {
        bg: brandScale[100],
        fg: brandScale[800],
        ring: brandScale[200],
        wash: brandScale[50],
      });
      continue;
    }
    const hue = (baseHue + slot.hueOffset + 360) % 360;
    setTintVars(root, slot.key, {
      bg: hslToTriplet(hue, Math.min(baseSat, 0.5), 0.92),
      fg: hslToTriplet(hue, Math.min(baseSat, 0.62), 0.34),
      ring: hslToTriplet(hue, Math.min(baseSat, 0.5), 0.84),
      wash: hslToTriplet(hue, Math.min(baseSat, 0.42), 0.965),
    });
  }

  const background = palette.background;
  root.setProperty("--app-bg", background.base);
  if (resolved.backgroundStyle === "plain") {
    root.setProperty("--app-bg-from", background.base);
    root.setProperty("--app-bg-via", background.base);
    root.setProperty("--app-bg-to", background.base);
  } else if (resolved.backgroundStyle === "warm") {
    root.setProperty("--app-bg-from", background.from);
    root.setProperty("--app-bg-via", background.to);
    root.setProperty("--app-bg-to", background.via);
  } else {
    root.setProperty("--app-bg-from", background.from);
    root.setProperty("--app-bg-via", background.via);
    root.setProperty("--app-bg-to", background.to);
  }

  const opacityPercent = resolved.watermarkEnabled
    ? Math.min(Math.max(resolved.watermarkOpacity, 0), MAX_WATERMARK_OPACITY_PERCENT)
    : 0;
  root.setProperty("--watermark-opacity", String(opacityPercent / 100));
}

function setTintVars(
  root: CSSStyleDeclaration,
  key: string,
  parts: { bg: string; fg: string; ring: string; wash: string },
) {
  root.setProperty(`--tint-${key}-bg`, parts.bg);
  root.setProperty(`--tint-${key}-fg`, parts.fg);
  root.setProperty(`--tint-${key}-ring`, parts.ring);
  root.setProperty(`--tint-${key}-wash`, parts.wash);
}


/** Hue (0..360) and saturation (0..1) of an "r g b" triplet. */
function rgbToHsl(triplet: string): [number, number, number] {
  const [r, g, b] = triplet.split(" ").map((value) => Number(value) / 255);
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const lightness = (max + min) / 2;
  const delta = max - min;
  if (delta === 0) return [0, 0, lightness];
  const saturation =
    lightness > 0.5 ? delta / (2 - max - min) : delta / (max + min);
  let hue: number;
  if (max === r) hue = ((g - b) / delta) % 6;
  else if (max === g) hue = (b - r) / delta + 2;
  else hue = (r - g) / delta + 4;
  hue = Math.round(hue * 60);
  if (hue < 0) hue += 360;
  return [hue, saturation, lightness];
}

/** Builds an "r g b" triplet from hue (0..360), saturation, lightness (0..1). */
function hslToTriplet(hue: number, saturation: number, lightness: number): string {
  const chroma = (1 - Math.abs(2 * lightness - 1)) * saturation;
  const huePrime = hue / 60;
  const x = chroma * (1 - Math.abs((huePrime % 2) - 1));
  let r = 0;
  let g = 0;
  let b = 0;
  if (huePrime < 1) [r, g, b] = [chroma, x, 0];
  else if (huePrime < 2) [r, g, b] = [x, chroma, 0];
  else if (huePrime < 3) [r, g, b] = [0, chroma, x];
  else if (huePrime < 4) [r, g, b] = [0, x, chroma];
  else if (huePrime < 5) [r, g, b] = [x, 0, chroma];
  else [r, g, b] = [chroma, 0, x];
  const m = lightness - chroma / 2;
  return [r, g, b]
    .map((channel) => Math.round((channel + m) * 255))
    .join(" ");
}

export function tripletToCss(triplet: string): string {
  return `rgb(${triplet.split(" ").join(" ")})`;
}
