import type { AppLanguage } from "./types";

const copy = {
  en: {
    navToday: "Today",
    navWorkflows: "Workflows",
    navHistory: "Activity",
    navSystem: "System",
    navSetup: "Setup",
    navSettings: "Hotel & settings",
    navSupport: "Support",
    shellLocal: "Local mode",
    shellConnected: "LifeDesk connected",
    shellPreview: "Browser preview",
    shellPreviewHint: "Desktop actions are available in npm run dev.",
    shellAttention: "Needs attention",
    shellWorking: "Automation running",
    homeEyebrow: "TODAY AT THE HOTEL",
    homeGreeting: "Good morning",
    homeTrustLocal: "Files stay at the hotel",
    homeTrustReview: "Every important action is reviewed",
    homeWorkTitle: "Choose the work, InnPilot guides the rest.",
    homeWorkText: "Two clear workflows cover the daily back-office work. Open one to review exactly what will happen before it starts.",
    invoicesKicker: "Invoices",
    invoicesTitle: "Prepare invoice files",
    invoicesText: "Find the right PDFs, prepare the output, and create reviewable Gmail drafts only when enabled.",
    documentsKicker: "Signed documents",
    documentsTitle: "Organize signed contracts",
    documentsText: "Collect scans, read them, and place recognized signed contracts in the right folder.",
    openWorkflow: "Open workflow",
    recentKicker: "LATEST RESULT",
    recentTitle: "Nothing has run yet",
    recentText: "The first safe rehearsal will appear here with a plain-language result.",
    recentOpen: "Review activity",
    readyAreas: "{ready} of {total} work areas ready",
    setupCompactTitle: "One short setup makes daily work effortless.",
    setupCompactText: "Connect the real folders once. InnPilot checks them before every run and never replaces existing files silently.",
    setupCompactAction: "Continue setup",
    runsCompleted: "completed runs",
    itemsHandled: "items handled",
    automationsEyebrow: "GUIDED WORKFLOWS",
    automationsTitle: "What should InnPilot do?",
    automationsText: "Start with the outcome. You will see a final review before any important local action.",
    dailyTitle: "Daily work",
    dailyText: "The two workflows staff should normally need.",
    toolsTitle: "Tools and access",
    toolsText: "Individual technical steps for setup or support. Keep this closed during normal work.",
    invoicesMode: "Current mode: {mode}",
    contractsSafety: "Scans are copied first. Originals remain in place during safe mode.",
    scansTitle: "Refresh local scans",
    scansText: "Copy available documents from the shared Scansioni folder to the protected local workspace.",
    ocrTitle: "Read scanned documents",
    ocrText: "Extract text locally so signed contracts can be recognized without uploading documents.",
    gmailTitle: "Reconnect Gmail",
    gmailText: "Reset this PC's Gmail authorization and sign in again. No email is sent automatically.",
    runSafe: "Review and start",
    reconnect: "Reconnect",
    fixSetup: "Fix setup",
    openFolder: "Open folder",
    ready: "Ready",
    blocked: "Setup needed",
    checking: "Checking",
    lastRun: "Last: {time}",
    noRun: "Not run yet",
    running: "Running safely",
    safeMode: "Safe mode",
    protected: "Local and protected",
    connectionNotReady: "Connect to LifeDesk",
  },
  it: {
    navToday: "Oggi",
    navWorkflows: "Flussi",
    navHistory: "Attività",
    navSystem: "Sistema",
    navSetup: "Configurazione",
    navSettings: "Hotel e impostazioni",
    navSupport: "Assistenza",
    shellLocal: "Modalità locale",
    shellConnected: "LifeDesk collegato",
    shellPreview: "Anteprima browser",
    shellPreviewHint: "Le funzioni desktop sono disponibili con npm run dev.",
    shellAttention: "Richiede attenzione",
    shellWorking: "Automazione in corso",
    homeEyebrow: "OGGI IN HOTEL",
    homeGreeting: "Buongiorno",
    homeTrustLocal: "I file restano in hotel",
    homeTrustReview: "Ogni azione importante viene controllata",
    homeWorkTitle: "Scegli il lavoro. InnPilot guida tutto il resto.",
    homeWorkText: "Due flussi chiari coprono il lavoro quotidiano di back office. Aprine uno per vedere esattamente cosa succederà prima di iniziare.",
    invoicesKicker: "Fatture",
    invoicesTitle: "Prepara i file fattura",
    invoicesText: "Trova i PDF corretti, prepara i file e crea bozze Gmail da controllare solo quando abilitate.",
    documentsKicker: "Documenti firmati",
    documentsTitle: "Organizza i contratti firmati",
    documentsText: "Raccoglie le scansioni, le legge e mette i contratti riconosciuti nella cartella corretta.",
    openWorkflow: "Apri il flusso",
    recentKicker: "ULTIMO RISULTATO",
    recentTitle: "Nessuna esecuzione",
    recentText: "La prima prova sicura apparirà qui con un risultato semplice da capire.",
    recentOpen: "Vedi attività",
    readyAreas: "{ready} di {total} aree pronte",
    setupCompactTitle: "Una configurazione breve rende il lavoro quotidiano immediato.",
    setupCompactText: "Collega una volta le cartelle reali. InnPilot le controlla prima di ogni esecuzione e non sostituisce mai file esistenti in silenzio.",
    setupCompactAction: "Continua configurazione",
    runsCompleted: "esecuzioni completate",
    itemsHandled: "elementi gestiti",
    automationsEyebrow: "FLUSSI GUIDATI",
    automationsTitle: "Cosa deve fare InnPilot?",
    automationsText: "Parti dal risultato. Prima di ogni azione locale importante vedrai un controllo finale.",
    dailyTitle: "Lavoro quotidiano",
    dailyText: "I due flussi che normalmente servono allo staff.",
    toolsTitle: "Strumenti e accessi",
    toolsText: "Singoli passaggi tecnici per configurazione o assistenza. Durante il lavoro normale questa sezione può restare chiusa.",
    invoicesMode: "Modalità attuale: {mode}",
    contractsSafety: "Le scansioni vengono prima copiate. In modalità sicura gli originali restano al loro posto.",
    scansTitle: "Aggiorna scansioni locali",
    scansText: "Copia i documenti disponibili dalla cartella Scansioni condivisa allo spazio locale protetto.",
    ocrTitle: "Leggi documenti scansionati",
    ocrText: "Estrae il testo in locale per riconoscere i contratti firmati senza caricare documenti online.",
    gmailTitle: "Ricollega Gmail",
    gmailText: "Reimposta l'autorizzazione Gmail di questo PC e accedi di nuovo. Nessuna email viene inviata automaticamente.",
    runSafe: "Controlla e avvia",
    reconnect: "Ricollega",
    fixSetup: "Completa configurazione",
    openFolder: "Apri cartella",
    ready: "Pronto",
    blocked: "Da configurare",
    checking: "Controllo",
    lastRun: "Ultima: {time}",
    noRun: "Mai eseguito",
    running: "Esecuzione sicura",
    safeMode: "Modalità sicura",
    protected: "Locale e protetto",
    connectionNotReady: "Collega LifeDesk",
  },
} as const;

export function operatorCopy(language: AppLanguage | undefined) {
  return language === "it" ? copy.it : copy.en;
}

export function fillCopy(value: string, values: Record<string, string | number>) {
  return value.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
